/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-02-25 13:07:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class weatherPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/views/menu/../layout/footer.jsp", Long.valueOf(1582622365000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

   request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("기상정보 페이지", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(function() {\r\n");
      out.write("        $(\"#weather\").empty();\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: \"weather\",\r\n");
      out.write("            type: \"POST\",\r\n");
      out.write("            success: function(xml) {\r\n");
      out.write("                var result = \"\";\r\n");
      out.write("                var idx = 0;\r\n");
      out.write("                $(xml).find(\"local\").each(function() {\r\n");
      out.write("                    if ($(this).text() == \"강릉\" || $(this).text() == \"서울\" || $(this).text() == \"대전\" || $(this).text() == \"대구\" || $(this).text() == \"부산\" || $(this).text() == \"울산\" || $(this).text() == \"원주\" || $(this).text() == \"제주\" || $(this).text() == \"인천\") {\r\n");
      out.write("                        if ($(this).text() == \"제주\") {\r\n");
      out.write("                            if ($(this).attr(\"desc\") == \"흐림\") {\r\n");
      out.write("                                $(\".weather_8\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름많음\") {\r\n");
      out.write("                                $(\".weather_8\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/many_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름조금\") {\r\n");
      out.write("                                $(\".weather_8\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"맑음\") {\r\n");
      out.write("                                $(\".weather_8\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"비\") {\r\n");
      out.write("                                $(\".weather_8\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/rain.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"박무\" || $(this).attr(\"desc\") == \"연무\") {\r\n");
      out.write("                                $(\".weather_8\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/mist.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"눈\") {\r\n");
      out.write("                                $(\".weather_8\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/snow.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $(\".weather_8\").css({\r\n");
      out.write("                                    \"background\": \"white\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        if ($(this).text() == \"부산\") {\r\n");
      out.write("                            if ($(this).attr(\"desc\") == \"흐림\") {\r\n");
      out.write("                                $(\".weather_7\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름많음\") {\r\n");
      out.write("                                $(\".weather_7\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/many_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름조금\") {\r\n");
      out.write("                                $(\".weather_7\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"맑음\") {\r\n");
      out.write("                                $(\".weather_7\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"비\") {\r\n");
      out.write("                                $(\".weather_7\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/rain.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"박무\" || $(this).attr(\"desc\") == \"연무\") {\r\n");
      out.write("                                $(\".weather_7\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/mist.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"눈\") {\r\n");
      out.write("                                $(\".weather_7\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/snow.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $(\".weather_7\").css({\r\n");
      out.write("                                    \"background\": \"white\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        if ($(this).text() == \"울산\") {\r\n");
      out.write("                            if ($(this).attr(\"desc\") == \"흐림\") {\r\n");
      out.write("                                $(\".weather_6\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름많음\") {\r\n");
      out.write("                                $(\".weather_6\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/many_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름조금\") {\r\n");
      out.write("                                $(\".weather_6\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"맑음\") {\r\n");
      out.write("                                $(\".weather_6\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"비\") {\r\n");
      out.write("                                $(\".weather_6\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/rain.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"박무\" || $(this).attr(\"desc\") == \"연무\") {\r\n");
      out.write("                                $(\".weather_6\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/mist.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"눈\") {\r\n");
      out.write("                                $(\".weather_6\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/snow.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $(\".weather_6\").css({\r\n");
      out.write("                                    \"background\": \"white\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        if ($(this).text() == \"대구\") {\r\n");
      out.write("                            if ($(this).attr(\"desc\") == \"흐림\") {\r\n");
      out.write("                                $(\".weather_5\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름많음\") {\r\n");
      out.write("                                $(\".weather_5\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/many_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름조금\") {\r\n");
      out.write("                                $(\".weather_5\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"맑음\") {\r\n");
      out.write("                                $(\".weather_5\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"비\") {\r\n");
      out.write("                                $(\".weather_5\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/rain.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"박무\" || $(this).attr(\"desc\") == \"연무\") {\r\n");
      out.write("                                $(\".weather_5\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/mist.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"눈\") {\r\n");
      out.write("                                $(\".weather_5\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/snow.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $(\".weather_5\").css({\r\n");
      out.write("                                    \"background\": \"white\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        if ($(this).text() == \"대전\") {\r\n");
      out.write("                            if ($(this).attr(\"desc\") == \"흐림\") {\r\n");
      out.write("                                $(\".weather_4\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름많음\") {\r\n");
      out.write("                                $(\".weather_4\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/many_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름조금\") {\r\n");
      out.write("                                $(\".weather_4\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"맑음\") {\r\n");
      out.write("                                $(\".weather_4\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"비\") {\r\n");
      out.write("                                $(\".weather_4\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/rain.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"박무\" || $(this).attr(\"desc\") == \"연무\") {\r\n");
      out.write("                                $(\".weather_4\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/mist.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"눈\") {\r\n");
      out.write("                                $(\".weather_4\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/snow.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $(\".weather_4\").css({\r\n");
      out.write("                                    \"background\": \"white\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        if ($(this).text() == \"원주\") {\r\n");
      out.write("                            if ($(this).attr(\"desc\") == \"흐림\") {\r\n");
      out.write("                                $(\".weather_3\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름많음\") {\r\n");
      out.write("                                $(\".weather_3\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/many_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름조금\") {\r\n");
      out.write("                                $(\".weather_3\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"맑음\") {\r\n");
      out.write("                                $(\".weather_3\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"비\") {\r\n");
      out.write("                                $(\".weather_3\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/rain.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"박무\" || $(this).attr(\"desc\") == \"연무\") {\r\n");
      out.write("                                $(\".weather_3\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/mist.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"눈\") {\r\n");
      out.write("                                $(\".weather_3\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/snow.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $(\".weather_3\").css({\r\n");
      out.write("                                    \"background\": \"white\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        if ($(this).text() == \"인천\") {\r\n");
      out.write("                            if ($(this).attr(\"desc\") == \"흐림\") {\r\n");
      out.write("                                $(\".weather_2\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름많음\") {\r\n");
      out.write("                                $(\".weather_2\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/many_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름조금\") {\r\n");
      out.write("                                $(\".weather_2\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"맑음\") {\r\n");
      out.write("                                $(\".weather_2\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"비\") {\r\n");
      out.write("                                $(\".weather_2\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/rain.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"박무\" || $(this).attr(\"desc\") == \"연무\") {\r\n");
      out.write("                                $(\".weather_2\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/mist.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"눈\") {\r\n");
      out.write("                                $(\".weather_2\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/snow.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $(\".weather_2\").css({\r\n");
      out.write("                                    \"background\": \"white\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        if ($(this).text() == \"서울\") {\r\n");
      out.write("                            if ($(this).attr(\"desc\") == \"흐림\") {\r\n");
      out.write("                                $(\".weather_1\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름많음\") {\r\n");
      out.write("                                $(\".weather_1\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/many_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름조금\") {\r\n");
      out.write("                                $(\".weather_1\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"맑음\") {\r\n");
      out.write("                                $(\".weather_1\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"비\") {\r\n");
      out.write("                                $(\".weather_1\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/rain.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"박무\" || $(this).attr(\"desc\") == \"연무\") {\r\n");
      out.write("                                $(\".weather_1\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/mist.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"눈\") {\r\n");
      out.write("                                $(\".weather_1\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/snow.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $(\".weather_1\").css({\r\n");
      out.write("                                    \"background\": \"white\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        if ($(this).text() == \"강릉\") {\r\n");
      out.write("                            if ($(this).attr(\"desc\") == \"흐림\") {\r\n");
      out.write("                                $(\".weather_0\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름많음\") {\r\n");
      out.write("                                $(\".weather_0\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/many_cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"구름조금\") {\r\n");
      out.write("                                $(\".weather_0\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/cloud.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"맑음\") {\r\n");
      out.write("                                $(\".weather_0\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/sun.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"비\") {\r\n");
      out.write("                                $(\".weather_0\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/rain.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"박무\" || $(this).attr(\"desc\") == \"연무\") {\r\n");
      out.write("                                $(\".weather_0\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/mist.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else if ($(this).attr(\"desc\") == \"눈\") {\r\n");
      out.write("                                $(\".weather_0\").css({\r\n");
      out.write("                                    \"background\": \"url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/weather/snow.png)\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            } else {\r\n");
      out.write("                                $(\".weather_0\").css({\r\n");
      out.write("                                    \"background\": \"white\",\r\n");
      out.write("                                    \"background-size\": \"100% 100%\"\r\n");
      out.write("                                });\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        result += \"<tr>\";\r\n");
      out.write("                        result += \"<td>\" + $(this).text() + \"</td>\";\r\n");
      out.write("                        result += \"<td id='\" + idx + \"'>\" + $(this).attr(\"desc\") + \"</td>\";\r\n");
      out.write("                        result += \"<td>\" + $(this).attr(\"ta\") + \"℃</td>\";\r\n");
      out.write("                        result += \"</tr>\";\r\n");
      out.write("                        idx++;\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                $(\"#weather\").append(result);\r\n");
      out.write("            },\r\n");
      out.write("            error: function() {\r\n");
      out.write("                alert(\"실패\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"weather_text\">\r\n");
      out.write("    <h1>전국 기상정보</h1>\r\n");
      out.write("    <br>\r\n");
      out.write("    <h3>전국의 기상정보를<br>확인 할 수 있습니다.</h3>\r\n");
      out.write("    <br><br><br><br><br>\r\n");
      out.write("    <h4>기상 정보는 3시간 주기로 업데이트 됩니다.</h4>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"weather_img\" id=\"weather_img\">\r\n");
      out.write("    <div class=\"weather_0\"></div>\r\n");
      out.write("    <div class=\"weather_1\"></div>\r\n");
      out.write("    <div class=\"weather_2\"></div>\r\n");
      out.write("    <div class=\"weather_3\"></div>\r\n");
      out.write("    <div class=\"weather_4\"></div>\r\n");
      out.write("    <div class=\"weather_5\"></div>\r\n");
      out.write("    <div class=\"weather_6\"></div>\r\n");
      out.write("    <div class=\"weather_7\"></div>\r\n");
      out.write("    <div class=\"weather_8\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"weather_t\">\r\n");
      out.write("    <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr style=\"text-align: center;\">\r\n");
      out.write("                <td width=\"200\">지역</td>\r\n");
      out.write("                <td width=\"200\">기상</td>\r\n");
      out.write("                <td width=\"200\">기온 (섭씨)</td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody id=\"weather\">\r\n");
      out.write("            <!-- ajax로 채워질 부분 -->\r\n");
      out.write("        </tbody>\r\n");
      out.write("        <tfoot>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"3\">\r\n");
      out.write("                    <b>※출처 기상청</b>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </tfoot>\r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\" style=\"position: absolute; width: 100%;\">\r\n");
      out.write("    <h4>약관 | 개인정보 | 저작권</h4>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
