/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-02-25 11:58:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/join/../layout/footer.jsp", Long.valueOf(1582622365000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1582621307568L));
    _jspx_dependants.put("jar:file:/Users/parkhansol/Desktop/spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("마이페이지", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(function() {\r\n");
      out.write("\r\n");
      out.write("        // 유효성 체크 (아이디, 주민번호, 이메일, 전화번호)\r\n");
      out.write("        var regExpId = /^[a-z]+[0-9a-z]{3,20}$/;\r\n");
      out.write("        var regExpSN = /^(?:[0-9]{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[1,2][0-9]|3[0,1]))-[1-4][0-9]{6}$/;\r\n");
      out.write("        var regExpEmail = /^[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*\\.[a-zA-Z]{2,3}$/i;\r\n");
      out.write("        var regExpTel = /^01(?:[0|1|6|7|8|9])-\\d{3,4}-\\d{4}$/;\r\n");
      out.write("\r\n");
      out.write("        var check1 = 0;   // 아이디 테스트\r\n");
      out.write("        var check3 = 0;   // 이메일 테스트\r\n");
      out.write("        var check4 = 0;   // 전화번호 테스트\r\n");
      out.write("        var check5 = 0;   // 비밀번호 테스트\r\n");
      out.write("        \r\n");
      out.write("        // 이메일 검사\r\n");
      out.write("        $(\"#userEmail\").keyup(function() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"emailCheck\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                data: \"userEmail=\" + $(\"#userEmail\").val(),\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    var obj = data;\r\n");
      out.write("\r\n");
      out.write("                    if (regExpEmail.test($(\"#userEmail\").val())) {\r\n");
      out.write("                        if (obj.emailCheckResult == \"1\") {\r\n");
      out.write("                            $(\"#emailCheckResult\").text(\"이미 가입된 이메일입니다.\");\r\n");
      out.write("                            $(\"#emailCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#emailCheckResult\").text(\"사용할 수 있는 이메일입니다.\");\r\n");
      out.write("                            $(\"#emailCheckResult\").css(\"color\", \"blue\");\r\n");
      out.write("                            check3 = 1;\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#emailCheckResult\").text(\"유효하지 않은 이메일형식 입니다\");\r\n");
      out.write("                        $(\"#emailCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                    }\r\n");
      out.write("                }, // end success\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        // 휴대폰번호 검사\r\n");
      out.write("        $(\"#userTel\").keyup(function() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"telCheck\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                data: \"userTel=\" + $(\"#userTel\").val(),\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    var obj = data;\r\n");
      out.write("\r\n");
      out.write("                    if (regExpTel.test($(\"#userTel\").val())) {\r\n");
      out.write("                        if (obj.telCheckResult == \"1\") {\r\n");
      out.write("                            $(\"#telCheckResult\").text(\"이미 가입된 휴대폰번호 입니다.\");\r\n");
      out.write("                            $(\"#telCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#telCheckResult\").text(\"사용할 수 있는 휴대폰번호 입니다.\");\r\n");
      out.write("                            $(\"#telCheckResult\").css(\"color\", \"blue\");\r\n");
      out.write("                            check4 = 1;\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#telCheckResult\").text(\"유효하지 않은 형식입니다('-' 포함)\");\r\n");
      out.write("                        $(\"#telCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                    }\r\n");
      out.write("                }, // end success\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 회원 정보 수정\r\n");
      out.write("        $(\"#changeInfoBtn\").click(function() {\r\n");
      out.write("            if ($(\"#userName\").val() == \"\") {\r\n");
      out.write("                swal(\"성명를 입력하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userAddr\").val() == \"\") {\r\n");
      out.write("                swal(\"주소를 입력하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userEmail\").val() == \"\" || check3 == 0) {\r\n");
      out.write("                swal(\"이메일을 확인하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userTel\").val() == \"\" || check4 == 0) {\r\n");
      out.write("                swal(\"연락처를 확인하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            f.action = \"infoModify\";\r\n");
      out.write("            f.submit();\r\n");
      out.write("        \t\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    }); // end 페이지로드\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"join_t\">\r\n");
      out.write("    <h1>회원 정보</h1>\r\n");
      out.write("    <form method=\"post\" id=\"f\">\r\n");
      out.write("        <table class=\"table table-striped\">\r\n");
      out.write("            <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>아이디</td>\r\n");
      out.write("                    <td style=\"height: 80px;\">\r\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDto.userId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                        <input type=\"hidden\" name=\"userIdx\" id=\"userIdx\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDto.userIdx }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><br>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>성명</td>\r\n");
      out.write("                    <td style=\"height: 80px;\"><input type=\"text\" name=\"userName\" id=\"userName\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDto.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><br></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>주소</td>\r\n");
      out.write("                    <td style=\"height: 80px;\">\r\n");
      out.write("                   \t\t<input type=\"text\" name=\"userAddr\" id=\"userAddr\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDto.userAddr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><br>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>이메일</td>\r\n");
      out.write("                    <td style=\"height: 80px;\">\r\n");
      out.write("                    \t<input type=\"text\" name=\"userEmail\" id=\"userEmail\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDto.userEmail }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><br>\r\n");
      out.write("                    \t<span id=\"emailCheckResult\"></span>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>전화번호</td>\r\n");
      out.write("                    <td style=\"height: 80px;\">\r\n");
      out.write("                    \t<input type=\"text\" name=\"userTel\" id=\"userTel\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDto.userTel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" /><br>\r\n");
      out.write("                    \t<span id=\"telCheckResult\"></span>\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tbody>\r\n");
      out.write("            <tfoot>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\">\r\n");
      out.write("                        <input type=\"button\" class=\"btn btn-primary\" value=\"회원정보수정\" id=\"changeInfoBtn\"/>\r\n");
      out.write("                        <input type=\"button\" class=\"btn btn-info\" value=\"비밀번호수정\" onclick=\"location.href='changePwPage?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginDto.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\" />\r\n");
      out.write("                        <input type=\"button\" class=\"btn btn-danger\" value=\"회원탈퇴하기\" onclick=\"location.href='leavePage'\" />\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </tfoot>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\" style=\"position: absolute; width: 100%;\">\r\n");
      out.write("    <h4>약관 | 개인정보 | 저작권</h4>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
