/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2020-02-25 10:17:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.join;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/join/../layout/footer.jsp", Long.valueOf(1582622365000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1582621307568L));
    _jspx_dependants.put("jar:file:/Users/parkhansol/Desktop/spring/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/team/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../layout/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("회원가입 페이지", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(function() {\r\n");
      out.write("\r\n");
      out.write("        // 유효성 체크 (아이디, 주민번호, 이메일, 전화번호)\r\n");
      out.write("        var regExpId = /^[a-z]+[0-9a-z]{3,20}$/;\r\n");
      out.write("        var regExpSN = /^(?:[0-9]{2}(?:0[1-9]|1[0-2])(?:0[1-9]|[1,2][0-9]|3[0,1]))-[1-4][0-9]{6}$/;\r\n");
      out.write("        var regExpEmail = /^[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_\\.]?[0-9a-zA-Z])*\\.[a-zA-Z]{2,3}$/i;\r\n");
      out.write("        var regExpTel = /^01(?:[0|1|6|7|8|9])-\\d{3,4}-\\d{4}$/;\r\n");
      out.write("        var isRobot = \"\";\r\n");
      out.write("      \r\n");
      out.write("        var check1 = 0;   // 아이디 테스트\r\n");
      out.write("\t    var check2 = 0;   // 주민등록번호 테스트\r\n");
      out.write("\t    var check3 = 0;   // 이메일 테스트\r\n");
      out.write("\t    var check4 = 0;   // 전화번호 테스트\r\n");
      out.write("\t    var check5 = 0;   // 비밀번호 테스트\r\n");
      out.write("        \r\n");
      out.write("        $(\"#userId\").keyup(function() {\r\n");
      out.write("\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"idCheck\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                data: \"userId=\" + $(\"#userId\").val(),\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("\r\n");
      out.write("                    var obj = data;\r\n");
      out.write("\r\n");
      out.write("                    if (regExpId.test($(\"#userId\").val())) {\r\n");
      out.write("                        if (obj.idCheckResult == \"1\") {\r\n");
      out.write("                            $(\"#idCheckResult\").text(\"이미 사용 중인 아이디입니다.\");\r\n");
      out.write("                            $(\"#idCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#idCheckResult\").text(\"이 아이디는 사용할 수 있습니다.\");\r\n");
      out.write("                            $(\"#idCheckResult\").css(\"color\", \"blue\");\r\n");
      out.write("                            check1 = 1;\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#idCheckResult\").text(\"4~20자, 소문자 시작, 소문자+숫자\");\r\n");
      out.write("                        $(\"#idCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                    }\r\n");
      out.write("                }, // end success\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            }); // end ajax\r\n");
      out.write("        }); // end keyup (end 아이디 중복체크)\r\n");
      out.write("\r\n");
      out.write("        // 주민등록번호 검사\r\n");
      out.write("        $(\"#userSN\").keyup(function() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"snCheck\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                data: \"userSN=\" + $(\"#userSN\").val(),\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    var obj = data;\r\n");
      out.write("\r\n");
      out.write("                    if (regExpSN.test($(\"#userSN\").val())) {\r\n");
      out.write("                        if (obj.SNCheckResult == \"1\") {\r\n");
      out.write("                            $(\"#SNCheckResult\").text(\"이미 가입된 주민등록번호입니다.\");\r\n");
      out.write("                            $(\"#SNCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#SNCheckResult\").text(\"사용할 수 있는 주민등록번호입니다.\");\r\n");
      out.write("                            $(\"#SNCheckResult\").css(\"color\", \"blue\");\r\n");
      out.write("                            check2 = 1;\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#SNCheckResult\").text(\"유효하지 않은 형식입니다.\");\r\n");
      out.write("                        $(\"#SNCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                    }\r\n");
      out.write("                }, // end success\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 이메일 검사\r\n");
      out.write("        $(\"#userEmail\").keyup(function() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"emailCheck\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                data: \"userEmail=\" + $(\"#userEmail\").val(),\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    var obj = data;\r\n");
      out.write("\r\n");
      out.write("                    if (regExpEmail.test($(\"#userEmail\").val())) {\r\n");
      out.write("                        if (obj.emailCheckResult == \"1\") {\r\n");
      out.write("                            $(\"#emailCheckResult\").text(\"이미 가입된 이메일입니다.\");\r\n");
      out.write("                            $(\"#emailCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#emailCheckResult\").text(\"사용할 수 있는 이메일입니다.\");\r\n");
      out.write("                            $(\"#emailCheckResult\").css(\"color\", \"blue\");\r\n");
      out.write("                            check3 = 1;\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#emailCheckResult\").text(\"유효하지 않은 이메일형식 입니다\");\r\n");
      out.write("                        $(\"#emailCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                    }\r\n");
      out.write("                }, // end success\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("        // 휴대폰번호 검사\r\n");
      out.write("        $(\"#userTel\").keyup(function() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"telCheck\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                data: \"userTel=\" + $(\"#userTel\").val(),\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    var obj = data;\r\n");
      out.write("\r\n");
      out.write("                    if (regExpTel.test($(\"#userTel\").val())) {\r\n");
      out.write("                        if (obj.telCheckResult == \"1\") {\r\n");
      out.write("                            $(\"#telCheckResult\").text(\"이미 가입된 휴대폰번호 입니다.\");\r\n");
      out.write("                            $(\"#telCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $(\"#telCheckResult\").text(\"사용할 수 있는 휴대폰번호 입니다.\");\r\n");
      out.write("                            $(\"#telCheckResult\").css(\"color\", \"blue\");\r\n");
      out.write("                            check4 = 1;\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#telCheckResult\").text(\"유효하지 않은 형식입니다('-' 포함)\");\r\n");
      out.write("                        $(\"#telCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("                    }\r\n");
      out.write("                }, // end success\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 비밀번호 검사\r\n");
      out.write("        $(\"#userPw2\").keyup(function() {\r\n");
      out.write("            if ($(\"#userPw\").val() != $(\"#userPw2\").val()) {\r\n");
      out.write("                $(\"#pwCheckResult\").text(\"비밀번호를 확인해주세요.\");\r\n");
      out.write("                $(\"#pwCheckResult\").css(\"color\", \"red\");\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#pwCheckResult\").text(\"비밀번호가 일치합니다.\");\r\n");
      out.write("                $(\"#pwCheckResult\").css(\"color\", \"blue\");\r\n");
      out.write("                check5 = 1;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // 회원 가입\r\n");
      out.write("        $(\"#joinBtn\").click(function() {\r\n");
      out.write("            if ($(\"#userId\").val() == \"\" || check1 == 0) {\r\n");
      out.write("                swal(\"아이디를 확인하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userPw\").val() == \"\" || check5 == 0) {\r\n");
      out.write("                swal(\"비밀번호를 확인하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userPw2\").val() == \"\" || check5 == 0) {\r\n");
      out.write("                swal(\"비밀번호를 확인하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userName\").val() == \"\") {\r\n");
      out.write("                swal(\"성명를 입력하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userSn\").val() == \"\" || check2 == 0) {\r\n");
      out.write("                swal(\"주민등록번호를 확인하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userAddr\").val() == \"\") {\r\n");
      out.write("                swal(\"주소를 입력하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userEmail\").val() == \"\" || check3 == 0) {\r\n");
      out.write("                swal(\"이메일을 확인하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if ($(\"#userTel\").val() == \"\" || check4 == 0) {\r\n");
      out.write("                swal(\"연락처를 확인하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if (isRobot == \"yes\" || isRobot == \"\") {\r\n");
      out.write("                swal(\"자동가입 방지과정을 진행하세요!\", \"\", \"error\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"join\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                data: $(\"#f\").serialize(),\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    var obj = data;\r\n");
      out.write("                    if (obj.joinResult == \"1\") {\r\n");
      out.write("                        swal({\r\n");
      out.write("                            title: \"가입에 성공했습니다. 로그인 페이지로 이동합니다.\",\r\n");
      out.write("                            text: \"\",\r\n");
      out.write("                            type: \"success\"\r\n");
      out.write("                        }).then(function() {\r\n");
      out.write("                            location.href = \"loginPage\";\r\n");
      out.write("                        });\r\n");
      out.write("                        //alert(\"가입에 성공했습니다. 로그인 페이지로 이동합니다.\")\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert(\"가입에 실패했습니다.\");\r\n");
      out.write("                    }\r\n");
      out.write("                }, // end success\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    alert(\"가입 실패\");\r\n");
      out.write("                }\r\n");
      out.write("            }); // end ajax\r\n");
      out.write("        }); // end click (end 회원 가입)\r\n");
      out.write("\r\n");
      out.write("        // 입력 취소\r\n");
      out.write("        $(\"#cleanBtn\").click(function() {\r\n");
      out.write("            $(\"input[text], input[password]\").each(function() {\r\n");
      out.write("                $(this).val(\"\");\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#idCheckResult\").val(\"\");\r\n");
      out.write("            $(\"#userId\").focus();\r\n");
      out.write("        }); // end click (end 입력 취소)\r\n");
      out.write("\r\n");
      out.write("        // 캡차 검사\r\n");
      out.write("        $(\"#checkImg\").click(function() {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: \"checkImg\",\r\n");
      out.write("                type: \"POST\",\r\n");
      out.write("                data: \"inputCaptcha=\" + $(\"#inputCaptcha\").val(),\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                success: function(data) {\r\n");
      out.write("                    var obj = data;\r\n");
      out.write("                    if (obj.captchaResult == true) {\r\n");
      out.write("                        swal(\"확인되었습니다.\", \"눈이 좋으시군요!\", \"success\");\r\n");
      out.write("                        isRobot = \"no\";\r\n");
      out.write("                    } else {\r\n");
      out.write("                        swal(\"확인에 실패하였습니다.\", \"로봇이신가요..?? 새로고침 후 다시 시도하세요\", \"error\");\r\n");
      out.write("                        isRobot = \"yes\";\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                error: function() {\r\n");
      out.write("                    //swal(\"오류발생!\", \"관리자에게 문의하세요\", \"info\");\r\n");
      out.write("                    alert(\"실패\");\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    }); // end 페이지로드\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"join_t\">\r\n");
      out.write("   <div id=\"login-page\" class=\"row\">\r\n");
      out.write("        <div class=\"\">\r\n");
      out.write("          <h2>회원가입</h2>\r\n");
      out.write("          <h4 class=\"center\">가입 후 예약 및 여러 회원들과 소통해보세요!</h4>\r\n");
      out.write("          <hr/>\r\n");
      out.write("        </div>\r\n");
      out.write("     <form id=\"f\" class=\"login-form\" method=\"post\" style=\"border-top: 1px solid #ccc;\">\r\n");
      out.write("         <div class=\"form-group\" style=\"text-align: left;\">\r\n");
      out.write("             <label for=\"userId\"><b>ID</b><span id=\"idCheckResult\"></span></label>\r\n");
      out.write("             <input class=\"form-control\" type=\"text\" id=\"userId\" name=\"userId\" autocomplete=\"off\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("   \r\n");
      out.write("         <div class=\"form-group\" style=\"text-align: left;\">\r\n");
      out.write("             <label for=\"userPw\"><b>Password</b></label>\r\n");
      out.write("             <input class=\"form-control\" type=\"password\" id=\"userPw\" name=\"userPw\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("   \r\n");
      out.write("         <div class=\"form-group\" style=\"text-align: left;\">\r\n");
      out.write("             <label for=\"userPw2\"><b>Password 확인</b><span id=\"pwCheckResult\"></span></label>\r\n");
      out.write("             <input class=\"form-control\" type=\"password\" id=\"userPw2\" name=\"userPw2\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("   \r\n");
      out.write("         <div class=\"form-group\" style=\"text-align: left;\">\r\n");
      out.write("             <label for=\"userName\"><b>Name</b></label>\r\n");
      out.write("             <input class=\"form-control\" type=\"text\" id=\"userName\" name=\"userName\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"form-group\" style=\"text-align: left;\">\r\n");
      out.write("             <label for=\"userSN\"><b>Serial Number (주민번호)</b><span id=\"SNCheckResult\"></span></label>\r\n");
      out.write("             <input class=\"form-control\" type=\"text\" id=\"userSN\" name=\"userSN\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"form-group\" style=\"text-align: left;\">\r\n");
      out.write("             <label for=\"userAddr\"><b>Address</b></label>\r\n");
      out.write("             <input class=\"form-control\" type=\"text\" id=\"userAddr\" name=\"userAddr\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"form-group\" style=\"text-align: left;\">\r\n");
      out.write("             <label for=\"userEmail\"><b>E-Mail</b><span id=\"emailCheckResult\"></span></label>\r\n");
      out.write("             <input class=\"form-control\" type=\"text\" id=\"userEmail\" name=\"userEmail\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"form-group\" style=\"text-align: left;\">\r\n");
      out.write("             <label for=\"userTel\"><b>Tel.</b><span id=\"telCheckResult\"></span></label>\r\n");
      out.write("             <input class=\"form-control\" type=\"text\" id=\"userTel\" name=\"userTel\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"form-group\">\r\n");
      out.write("          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/captcha/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tempname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"캡차이미지\" id=\"captchaImg\" class=\"captchaImg\">\r\n");
      out.write("          <br/>\r\n");
      out.write("          <div style=\"margin-top:15px;\">\r\n");
      out.write("             <button type=\"button\" style=\"padding: 35px 20px 0 20px;\" class=\"btn btn-search btn-lg\" onclick=\"location.href='joinPage'\" >\r\n");
      out.write("              <span class=\"glyphicon glyphicon-refresh\" aria-hidden=\"true\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <input class=\"form-control\" type=\"text\" name=\"inputCaptcha\" id=\"inputCaptcha\" required placeholder=\"문자 또는 숫자를 입력하세요.\" style=\"width: 310px; height:60px; margin:auto;\">\r\n");
      out.write("            <input type=\"button\" value=\"확인\" id=\"checkImg\" class=\"btn btn-primary\" style=\"width: 100px; height: 60px;\"/>\r\n");
      out.write("         </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div style=\"margin-top: 10px;\">\r\n");
      out.write("          <input type=\"button\" value=\"회원가입\" id=\"joinBtn\" class=\"btn btn-success btn-lg\" style=\"padding: 10px;\"/>\r\n");
      out.write("          &nbsp;&nbsp;\r\n");
      out.write("          <input type=\"reset\" value=\"입력취소\" id=\"cleanBtn\" class=\"btn btn-warning btn-lg\" style=\"padding: 10px;\"/>\r\n");
      out.write("         <br/><br/>\r\n");
      out.write("          <p>이미 가입하신 회원이십니까? <a href=\"loginPage\">로그인하러 가기</a></p>\r\n");
      out.write("          </div>\r\n");
      out.write("   \r\n");
      out.write("       </form>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\" style=\"position: absolute; width: 100%;\">\r\n");
      out.write("    <h4>약관 | 개인정보 | 저작권</h4>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
